src/modules/mimeapp/mime_app.cpp

如果用户有通过控制中心修改默认程序，每次重新登录系统使用之前用户设置的默认程序
而不是从配置文件中重新加载
Log: 修复注销系统后默认程序设置失效的问题
Bug: https://github.com/linuxdeepin/developer-center/issues/3591
Influence: 控制中心默认程序设置

fix: 注销系统后默认程序设置失效

---

src/modules/launcher/launcher.cpp
src/modules/launcher/launcher.h

This reverts commit f1ac5f9f00a490635c06c05dcef7539e7fc3ed59.
Fixes linuxdeepin/developer-center#3617
Log: 修复 launcher 无法记住全屏状态

Revert "feat: 社区差异化需求实现"

---

src/lib/xcbutils.cpp

fix https://github.com/linuxdeepin/developer-center/issues/3763 
the full character which `xcb_ewmh_get_wm_name` returns  is longer than wm name,
get the same length character as the wm name instead of full character .
log:

fix: fix get a longer name then it actually is

---

src/modules/dock/windowidentify.cpp
src/modules/dock/windowinfobase.h
src/modules/dock/windowinfox.cpp

对于某些没有提供desktop文件（或者desktop文件中没有指定Icon字段）的应用
需要从窗管获取应用的Icon
Log: 修复任务栏应用图标显示异常的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/3811
Influence: 任务栏应用图片显示

fix: 任务栏应用图标显示异常

---

src/modules/dock/windowinfox.cpp

Add a check when `buf` is nullptr to avoid exit.
TODO: I don't know why.

fix: Crashed when get windowicon

---

.reuse/dep5
.tx/deepin.conf
debian/changelog

* fix get a longer name then it actually is
* fix abnormal icon display in the dock
* set fullscreen launcher by default
* fix default application resets after relogin
* fix crash when get windowicon
* fix app proxy invalid
* fix invalid appid

chore: bump version to 1.0.9

---

src/lib/desktopfile.cpp
src/lib/desktopfile.h
src/lib/desktopinfo.cpp
src/lib/desktopinfo.h
src/lib/keyfile.cpp
src/lib/keyfile.h
src/modules/dock/appinfo.cpp
src/modules/launcher/launcher.cpp
src/modules/startmanager/startmanager.cpp

KeyFile::saveToFile not guaranteed section order, which is not the right
behavior of desktop file. XDG requires the first section of desktop file
always to be "Desktop Entry".
So I write a new DesktopFile class, which override the saveToFile method
of KeyFile, to make it work.
close linuxdeepin/developer-center#3807

Improve desktop file handling

---

src/modules/startmanager/startmanager.cpp

此处不应该将多个文件的路径拼接成一个异常(不存在)的路径,
而应该将多个文件的路径分开传入
Log: 修复应用无法打开选中的多个文件的问题
Reslove: https://github.com/linuxdeepin/developer-center/issues/4005
Influence: 应用打开多个文件

fix: 应用无法打开选中的多个文件

---

src/modules/launcher/launcher.cpp

1. 修复使用ll-cli终端卸载玲珑应用后，启动器图标依然存在的问题。
2. 修复右键点击启动器图标卸载玲珑应用，发送到桌面的文件依然存在的问题。
close #developer-center/issues/3611

fix: 卸载玲珑应用时，部分行为异常

---

debian/control
src/lib/xcbutils.cpp
src/modules/dock/windowidentify.cpp
src/modules/dock/windowidentify.h
src/modules/startmanager/startmanager.cpp
src/service/CMakeLists.txt

Code copy from https://gitlab.gnome.org/GNOME/metacity/-/merge_requests/13/diffs
The xprop `_NET_WM_PID` is set by the client side, even if the process
in running in some container. But when pid_ns is unshared, the processes
in side a container, will not be able to get the "right" pid of itself.
The "new" XResQueryClientIds added to XRes will fix this issue by
produce the pid in server side.
refs:
- https://gitlab.freedesktop.org/xorg/xserver/-/issues/1022#note_497597
- https://www.x.org/releases/X11R7.7/doc/resourceproto/resproto.txt
close linuxdeepin/developer-center#3802

fix some window identify issues

---

src/modules/dock/common.h
src/modules/dock/dbushandler.cpp
src/modules/dock/dock.cpp
src/modules/dock/windowidentify.cpp

The bamfdaemon is needs X server, it's crash on XWayland.

fix: don't use bamf on wayland session

---

src/lib/xcbutils.cpp
src/lib/xcbutils.h
src/modules/dock/windowinfox.cpp

使用xcb ewmh的相关接口获取应用icon
Log: 修复没有图标的应用退出时AM奔溃退出的问题
Influence: 任务栏应用图标正常显示

fix: 退出没有图标的应用AM崩溃

---

src/modules/startmanager/startmanager.cpp

Recognized args should be removed from exec args when there are no actual contents. instead of being replaced by "".
Log: fix error handling recognized args

fix: error handling recognized args

---

src/modules/dock/windowidentify.cpp

If we cannot get desktop file from env, we should just failed.

fix: early return in WindowIdentify::identifyWindowByPidEnv

---

src/lib/applaunchcontext.h
src/lib/keyfile.h

Clang need these header to be included for definition of uint32_t and
uint64_t.

fix: add missing header for clang

---

src/modules/launcher/launcher.cpp

When we install the package which binary packed in /opt, the trigger will link the desktop file and binary to /usr. 
But it links desktop file first and AM can not find the program of the package in any path of $PATH at that moment. Then the signal which named ItemChanged is not emited by AM and launcher will not display the icon.
This is a quick fix, wait 1000ms until the binary link is complete.
close: linuxdeepin/developer-center#4487

fix: icon is not displayed after a package installed

---

src/lib/xcbutils.cpp

The correct size is width * height instead of 2 + width * height.
Log:

fix: heap buffer overflow

---

src/modules/startmanager/startmanager.cpp
src/modules/startmanager/startmanager.h

linuxdeepin/developer-center#4412
QProcess::execute will use waitid to get exit code of that process it
starts. Register SIG_CHILD and wait all dead childs will break this
mechanism, as QProcess will find out that there is no child to wait,
and report this situation as a child process exit by crash.
So I change the method of launch application to use a double fork, to
start process and detach. Just as the way `QProcess` get this job done
in its `startDetached` method.
As a quick fix, I change the signature of `launch` method as no one use
its return value currently. If this is need someday, we should use a
pipe to let double forked child process report the return value and
errno of its `exec` call.

 fix: void register signal handler for SIG_CHILD

---

src/modules/launcher/common.h
src/modules/launcher/launcher.cpp

不以完整路径来检查进行卸载请求的应用是不是 dde-launcher。
注意，这里原本进行的检查本身是不合理的，本身也很容易被绕过。后续应当以其他的形式确保卸载接口不被滥用。

fix: don't check full path for launcher

---

src/modules/startmanager/startmanager.cpp

Multiple thread process will have only one active thread after fork.
It means that if other thread hold a locked mutex before we fork, it
will take forever for that thread unlock the mutex.

fix: do not log in child process after fork

---

src/modules/launcher/launcher.cpp

应该使用m_desktopAndItemMap而不是itemsMap去获取对应的Item
Log: 修复卸载第三方应用后任务栏依然显示应用的问题
Influence: 任务栏应用正常显示
Resolve: https://github.com/linuxdeepin/developer-center/issues/4630

fix: 卸载第三方应用后任务栏依然显示应用

---

src/lib/keyfile.cpp

Calling line.front() on an empty line is forbidden and crashes the process. Adding checks after erasing spaces from the line.
```
(gdb) bt
#0  0x00007ffff568e83c in  () at /usr/lib/libc.so.6
#1  0x00007ffff563e668 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff56264b8 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff5add3b2 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
(file=file@entry=0x7ffff5bd7858 "/usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h", line=line@entry=1305, function=function@entry=0x7ffff5bd79d0 "std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocat"..., …
```

fix: crash when autostart desktop file contains an empty line

---

src/lib/utils.cpp

std::vector<>::push_back() doesn't accept multiple elements and crashes due to incompatible type being provided. Let's just push twice.

fix: crash when XDG_DATA_DIRS is unset

---

src/dbus/applicationservice.cpp

m_environ maybe empty when it is be set more than once.
and the key is already exists in storage.

fix: can't write environ to storage

---

src/dbus/applicationmanager1service.cpp
src/dbus/applicationmanager1service.h

Restart timer to merge directory changed and dpkg hook event. Reload applications when called from dbus.
issue: https://github.com/linuxdeepin/developer-center/issues/7830

fix: missing package parsed when ReloadApplicaitons

---

src/dbus/applicationservice.cpp

incorrect information was set for key:  'X-Deepin-GenerateSource'
Issue: https://github.com/linuxdeepin/developer-center/issues/7637

fix: self start setting failed

---

src/dbus/applicationmanager1service.cpp
src/global.h
src/systemdsignaldispatcher.cpp

Do not filter out those not launched by application manager. Assume unit name as the app id. When Identify, assume there is only one unique instance.
Log: support apps launched directly by systemd
Related-to: https://github.com/linuxdeepin/developer-center/issues/8088

feat: support apps launched directly by systemd

---

src/dbus/applicationservice.cpp

QUrl("/tmp/xxx.png").toLocalFile() is Empty..
Issue: https://github.com/linuxdeepin/developer-center/issues/8142

fix: dde-open file failed

---

debian/control
misc/CMakeLists.txt
misc/hooks.d/2-debFix.json.in
misc/hooks.d/debFix.sh
src/dbus/applicationmanager1service.cpp

Add a hook to solve the problem of not being able to start some startup scripts for applications without shebang
Log:

feat: Add a hook and wrap all applications in the hook script to start

---

src/dbus/applicationservice.cpp

if parameters are empty, remove "%abc" in command
Issue: https://github.com/linuxdeepin/developer-center/issues/8481
Issue: https://github.com/linuxdeepin/developer-center/issues/8482

fix: dman display nothing

---

src/dbus/applicationservice.cpp

when the name contains a single space, the command parse raises the issue.
Issue: https://github.com/linuxdeepin/developer-center/issues/8498

fix: revert "crashed when removing a invalid index"

---

debian/changelog
src/dbus/applicationmanager1service.cpp

xdg 自启动目录下有些desktop文件有 Hidden 字段没有 GenerateSource
导致调用为构造的app(nullptr)
Issue: https://github.com/linuxdeepin/developer-center/issues/8523

fix: crash when desktop file has "Hidden"

---

debian/changelog
src/dbus/applicationservice.cpp

reutrn {} at end of std::vector<MimeInfo>
Issue: https://github.com/linuxdeepin/developer-center/issues/8598

fix: open terminal with shortcut for first time crashed

---

src/dbus/mimemanager1service.cpp

sendErrorReply if not found..
https://github.com/linuxdeepin/dde-application-manager/pull/208 就是没有检查导致崩溃的。这个还是要有的

chore: check std::find_if result

---

misc/hooks.d/debFix.sh

Rewrite this script to make it easier to read and disable full-text scan when the executable is not even a text
Related link: https://bbs.deepin.org.cn/post/272738

adjust: Fix use too long time when starting apps

---

debian/changelog
misc/CMakeLists.txt
misc/systemd/user/app-DDE-.service.d/override.conf

添加 systemd drop-in 文件，将 app-DDE- 开头的
服务退出超时时间设置为 3s
Issues: linuxdeepin/developer-center#8554

chore: set apps quit timeout to 3s

---

api/dbus/org.desktopspec.ApplicationManager1.Application.xml
apps/app-launch-helper/src/main.cpp
apps/app-launch-helper/src/variantvalue.cpp
misc/CMakeLists.txt
misc/dsg/configs/dde-application-manager/org.deepin.dde.application-manager.json
src/constant.h
src/dbus/CMakeLists.txt
src/dbus/applicationservice.cpp
src/launchoptions.cpp
src/launchoptions.h

to fix #8667 you can
- subpath:"/FoxitReader" appExtraEnvironments : "QT_QPA_PLATFORM=xcb"
- subpath:"/FoxitReader" appEnvironmentsBlacklist : "QT_QPA_PLATFORM"
```
dde-dconfig set -a org.deepin.dde.application-manager -r org.deepin.dde.application-manager -k appExtraEnvironments -s "/FoxitReader" -v "[\"QT_QPA_PLATFORM=xcb\"]"
dde-dconfig set -a org.deepin.dde.application-manager -r org.deepin.dde.application-manager -k appEnvironmentsBlacklist -s "/FoxitReader" -v "[\"QT_QPA_PLATFORM\"]"
```
Issue: https://github.com/linuxdeepin/developer-center/issues/8667

feat: add app extra env config

---

src/dbus/applicationservice.cpp

初次启动时对比filepath 还需要看看 X-Deepin-GenerateSource
Issue: https://github.com/linuxdeepin/developer-center/issues/9638

fix: deepin-home checkauto start failed

---

debian/changelog

bump version 1.2.17
log: as title

chore: bump version 1.2.17

---

apps/app-identifier/src/main.cpp

pidfd must be closed by caller according QDBusUnixFileDescriptor.

fix: pidfd leak

---

api/dbus/org.desktopspec.ApplicationManager1.Application.xml
api/dbus/org.desktopspec.ApplicationManager1.xml
src/dbus/applicationmanager1service.cpp
src/dbus/applicationmanager1service.h
src/dbus/applicationservice.cpp
src/dbus/applicationservice.h
src/dbus/mimemanager1service.cpp
src/dbus/mimemanager1service.h

没有添加用户程序接口
Log:
pms: BUG-292937

fix: 修复默认程序里无法添加新下载的应用和系统应用问题

---

src/dbus/applicationservice.cpp

unescapeExecArgs()函数中使用了遵循POSIX标准的wordexp，可以正确解析被引号包裹的整体，解析成参数列表, 被分割的都是一个个整体，若分割后的参数在这里还能再按空格分割，则说明这个参数被包裹在一个引号中作为了一个整体，此时我们不能再分割这个参数
pms: BUG-307881

fix: abnormal splitting of parameters enclosed in quotation marks in Exec

---

debian/changelog

as title
Log: bump version to 1.2.26

chore: bump version to 1.2.26
