- misc/dconf/com.deepin.dde.launcher.json
> feat: set fullscreen launcher by default

- CMakeLists.txt
- misc/CMakeLists.txt
- misc/dconf/CMakeLists.txt
- misc/service/dde-application-manager.service
- misc/systemd/org.deepin.dde.Application1.Instance@.service
- misc/systemd/org.deepin.dde.Application1.Manager.service
- src/loader/CMakeLists.txt
- src/loader/main.cpp
- src/service/CMakeLists.txt
- src/service/impl/application_manager.cpp
rename project to dde-application-manager
log:
> chore: rename project to dde-application-manager

- src/modules/startmanager/startmanager.cpp
- src/modules/startmanager/startmanagerdbushandler.cpp
AddProxyProc for launched app by launcher.
Issue: https://github.com/linuxdeepin/developer-center/issues/3791
> fix: App proxy invalid

- .tx/config
update the transifex config file
> chore: update the transifex config file

- src/modules/launcher/launcher.cpp
修改了将参数以字符串拼接形式传入process.start中的问题，避免了命令注入。
Log: 修改了process.start函数参数的问题
> fix: 修改了process.start函数参数的问题

- src/modules/mimeapp/mime_app.cpp
- src/modules/mimeapp/mime_app.h
Moved to linuxdeepin/default-settings#30
> chore: don't initialize the default applications

- src/modules/dock/dock.cpp
部分修复了两种场景：
- 无法点击图标打开的锯齿应用在系统启动时残留在最近任务栏（如Deepin-Lock）
- 锯齿图标应用被关闭后，残留在最近任务栏．（如dde-dconfig-editor）
当前存在问题：
第二种情况在锯齿应用被移除时，任务栏会闪一下．
Issue: https://github.com/linuxdeepin/developer-center/issues/3788
Log: 任务栏最近使用任务区域残留锯齿图标应用
> fix: 任务栏最近使用任务区域残留锯齿图标应用

- src/modules/startmanager/startmanager.cpp
Supported HiDPI for the deepin wine applications. We must give an env variant to apply the window scale effect to it.
> fix: set DEEPIN_WINE_SCALE on launch an application

- src/modules/launcher/launcher.cpp
- src/modules/startmanager/startmanager.cpp
- src/modules/startmanager/startmanager.h
> fix GIO_LAUNCHED_DESKTOP_FILE_PID

- src/modules/startmanager/startmanager.cpp
QProcess::arguments do not contain arg[0].
Signed-off-by: black-desk <me@black-desk.cn>
> fix: arg[0] should be program exe

- debian/control
- src/lib/dstring.cpp
- src/lib/dstring.h
- src/lib/process.cpp
- src/loader/CMakeLists.txt
- src/service/CMakeLists.txt
> fix: use jemalloc to temporary circumvention of crash issues

- debian/changelog
> chore: bump version 1.0.13

- src/modules/apps/alrecorder.cpp
- src/modules/dock/dock.cpp
- src/modules/dock/processinfo.cpp
- src/modules/dock/windowidentify.cpp
- src/modules/launcher/launcher.cpp
- src/modules/startmanager/startmanager.cpp
>  修复desktop名称获取错误问题

- debian/changelog
> chore: bump version 1.0.15

- src/modules/dock/entries.cpp
Signed-off-by: black-desk <me@black-desk.cn>
> fix: fix a use-after-free

- debian/changelog
> chore: bump version 1.0.16

- src/lib/applaunchcontext.cpp
- src/modules/dock/docksettings.h
Should add some default statements in src/lib/applaunchcontext.cpp and src/modules/dock/docksettings.h
Log:
> fix: missing return statements

- debian/changelog
> chore: bump version 1.0.17

- src/modules/dock/dock.cpp
Resolve: https://github.com/linuxdeepin/developer-center/issues/4725
Log: 修复自定义shell脚本无法执行
> fix: fix custom shellscript can't be executed

- debian/changelog
> chore: bump version 1.0.18

- src/modules/launcher/launcher.cpp
- translations/dde-application-manager.ts
- translations/dde-application-manager_zh_CN.ts
Issue: https://github.com/linuxdeepin/dde-launcher/issues/362
> Update package removal notification icon and copywriting

- src/CMakeLists.txt
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/dbus/instanceservice.cpp
- src/dbus/instanceservice.h
- src/dbus/jobmanager1service.cpp
- src/dbus/jobmanager1service.h
- src/dbus/jobservice.cpp
- src/dbus/jobservice.h
> feat: init dbus service structure

- api/dbus/org.desktopspec.JobManager1.Job.xml
- src/dbus/jobservice.cpp
- src/dbus/jobservice.h
> feat: implement job service

- src/desktopentry.cpp
- src/include/desktopentry.h
> feat: add desktopentry class

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/dbus/instanceservice.cpp
- src/dbus/instanceservice.h
- src/dbus/jobmanager1service.cpp
- src/dbus/jobmanager1service.h
- src/dbus/jobservice.cpp
- src/dbus/jobservice.h
- src/include/global.h
> feat: adjust dbus service structure

- CMakeLists.txt
- api/dbus/org.desktopspec.JobManager1.Job.xml
- api/dbus/org.desktopspec.JobManager1.xml
- src/CMakeLists.txt
- src/dbus/jobmanager1service.cpp
- src/dbus/jobmanager1service.h
- src/dbus/jobservice.cpp
- src/dbus/jobservice.h
- src/include/global.h
> feat: finish dbus service: job/jobManager

- docs/TODO.md
Add some plan date and correct some mistakes.
> docs: update TODO

- CMakeLists.txt
- api/dbus/org.desktopspec.ApplicationManager1.xml
- apps/app-launch-helper/src/CMakeLists.txt
- apps/app-launch-helper/src/main.cpp
- apps/dde-application-manager/src/main.cpp
- apps/dde-application-manager/src/utils.cpp
- docs/TODO.md
- examples/CMakeLists.txt
- examples/launchApp/CMakeLists.txt
- examples/launchApp/main.cpp
- src/cgroupsidentifier.cpp
- src/cgroupsidentifier.h
- src/constant.h
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/dbus/instanceservice.h
- src/dbus/jobmanager1service.cpp
- src/dbus/jobmanager1service.h
- src/desktopentry.cpp
- src/desktopentry.h
- src/global.h
- src/systemdsignaldispatcher.cpp
- src/systemdsignaldispatcher.h
- tests/CMakeLists.txt
- tests/ut_desktopentry.cpp
details refer to commit message.
> feat: add SystemdSignalDispathcer and implementation of UpdateApplicationInfo

- CMakeLists.txt
- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- api/dbus/org.desktopspec.ApplicationManager1.Instance.xml
- api/dbus/org.desktopspec.ApplicationManager1.xml
- api/dbus/org.desktopspec.ObjectManager1.xml
- apps/app-launch-helper/src/main.cpp
- apps/dde-application-manager/src/main.cpp
- examples/launchApp/main.cpp
- src/constant.h
- src/dbus/CMakeLists.txt
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/dbus/jobmanager1service.cpp
- src/dbus/jobmanager1service.h
- src/dbus/jobservice.cpp
- src/desktopentry.cpp
- src/desktopentry.h
- src/global.h
- tests/ut_applicationmanager.cpp
- tests/ut_desktopentry.cpp
- tests/ut_job.cpp
- tests/ut_jobmanager.cpp
- tools/profiling.sh
- tools/test-coverage.sh
1. remove method: Application, Launch. (ApplicationManager1)
2. add property: IconName, DisplayName. (Application1)
3. refact the way of construct ApplicationService.
4. if Desktop Entry Key `Hidden` is true, this application wouldn't export to DBus.
> feat: change dbus interface api

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- apps/dde-application-manager/src/main.cpp
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/desktopentry.cpp
- src/desktopentry.h
- src/global.h
- src/systemdsignaldispatcher.cpp
1. reactor some utils implementation.
2. remove constexpr before `decltype(auto)` due to GCC bug.
refer: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102229
> feat: add property "LastLaunchedTime" 

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/desktopentry.cpp
- src/desktopentry.h
- src/global.h
- tests/ut_applicationmanager.cpp
and fix incorrect behavior when launch application by other action.
> feat: add property installedTime,X-flatpak,X-linglong

- misc/systemd/user/org.deepin.dde.ApplicationManager1.service.in
- src/dbus/applicationmanager1service.cpp
- src/desktopentry.cpp
- src/global.h
fix AM can't access some dirs due to systemd 254's sandboxing option: PrivateUser is true by default.
refer: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateUsers=
> refact: remove unnecessary open operation

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- misc/CMakeLists.txt
- misc/dbus/org.desktopspec.ApplicationManager1.service.in
- misc/systemd/user/org.desktopspec.ApplicationManager1.service.in
- src/constant.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/global.h
> add some interface method/property and change AM service Name

- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationservice.cpp
others refer to commit messages.
> refact: method Launch and updateApplicationInfo

- api/dbus/org.desktopspec.ApplicationManager1.xml
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
others refer to commit messages.
> refactor autostart and ReloadApplications

- .reuse/dep5
- apps/app-update-notifier/misc/CMakeLists.txt
- apps/app-update-notifier/misc/dbus/org.desktopspec.ApplicationUpdateNotifier1.conf
- apps/app-update-notifier/misc/dbus/org.desktopspec.ApplicationUpdateNotifier1.service.in
- apps/app-update-notifier/misc/systemd/system/org.desktopspec.ApplicationUpdateNotifier1.service.in
- debian/changelog
- misc/CMakeLists.txt
- misc/dpkg/dpkg.cfg.d/am-update-hook
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationservice.cpp
> chore: release 0.2.0

- CMakeLists.txt
- debian/changelog
- misc/dpkg/dpkg.cfg.d/am-update-hook
add || true to satisfy dpkg hook
> fix(am-update-hook): always success

- src/cgroupsidentifier.cpp
- src/cgroupsidentifier.h
- src/dbus/applicationmanager1service.cpp
- src/desktopentry.cpp
- src/desktopentry.h
- src/global.h
details refer to commit messages.
> resolve some todo and fixme

- src/dbus/applicationmanager1service.cpp
- src/global.h
- src/propertiesForwarder.cpp
details refer to commit message.
> fix and refactor some method implements

- api/dbus/org.desktopspec.ApplicationManager1.Instance.xml
- api/dbus/org.desktopspec.ApplicationManager1.xml
- apps/dde-application-manager/src/main.cpp
- src/applicationmanagerstorage.cpp
- src/applicationmanagerstorage.h
- src/cgroupsidentifier.cpp
- src/constant.h
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/dbus/instanceservice.cpp
- src/dbus/instanceservice.h
- src/desktopentry.cpp
- src/desktopentry.h
- src/global.h
- src/propertiesForwarder.cpp
- src/systemdsignaldispatcher.cpp
- tests/main.cpp
- tests/ut_applicationmanager.cpp
- tests/ut_job.cpp
details refer to commit message
> add persistent storage and refactor some method

- src/dbus/applicationmanager1service.cpp
> fix: should't move singelSlot

- CMakeLists.txt
> chore: correct typo in project description of CMakeLists.txt

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- api/dbus/org.desktopspec.ApplicationManager1.xml
- src/constant.h
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
- src/desktopentry.cpp
- src/desktopentry.h
- src/desktopfilegenerator.cpp
- src/desktopfilegenerator.h
- src/desktopfileparser.cpp
- src/desktopfileparser.h
- src/global.h
- tests/ut_desktopfilegenerator.cpp
1. change type of ActionName to 'a{sa{ss}}'
2. refactor the method of serialization
> feat: add desktopfilegenerator and method addUserApplication

- src/applicationmanagerstorage.cpp
- src/applicationmanagerstorage.h
- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationservice.cpp
issue: https://github.com/linuxdeepin/developer-center/issues/5768
> refact: assuming all applications have been launched during AM create storage at first time

- debian/changelog
- src/applicationmimeinfo.cpp
- src/dbus/mimemanager1service.cpp
issue: https://github.com/linuxdeepin/developer-center/issues/6794
> fix: create user's mimeapp when it doesn't exists

- debian/control
> chore: update debian/control

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
> chore: correct typo

- README.md
- README.zh_CN.md
> chore: update README.md

- src/dbus/applicationservice.cpp
GDK_SCALE 缩放 UI
GDK_DPI_SCALE 缩放字体，
同时设置后太大了，只需要缩放 UI 即可，字体会适应大小
Isuee: https://github.com/linuxdeepin/developer-center/issues/7528
> fix: gtk app scaled size too big

- src/dbus/applicationservice.cpp
fallback to pre-value when it's valid.
> fix: wrong InstalledTime for application

- src/dbus/applicationservice.cpp
`QT_SCREEN_SCALE_FACTOR` ==> `QT_SCREEN_SCALE_FACTORS`
see https://doc.qt.io/qt-5/highdpi.html
QT_SCREEN_SCALE_FACTORS=1.25;1.25
QT_SCALE_FACOTR=1.25
> chore: use QT_SCALE_FACOTR set scale factor 

- .gitignore
- debian/changelog
>  chore: bump version to 1.2.1

- debian/changelog
> chore: bump version to 1.2.2

- src/dbus/applicationservice.cpp
Signed-off-by: ComixHe <heyuming@deepin.org>
> fix: take GIO env back

- debian/changelog
release 1.2.3
Log: bump version to 1.2.3
> chore: bump version to 1.2.3

- debian/changelog
> chore: bump version to 1.2.4

- src/dbus/mimemanager1service.cpp
Log: Return correct mimetype and default app for directories
> fix: Return correct mimetype and default app for directories

- debian/changelog
bump version to 1.2.5
Log: update changelog
> chore: bump version to 1.2.5

- debian/control
- src/dbus/applicationmanager1service.cpp
- check TryExec when doReloadApplications
- add deepin-deb-fix to Suggested dependency
> feat: Can emit correct remove signal when uninstalling applications patched by deepin-deb-fix

- debian/changelog
> chore: dump version to 1.2.6

- debian/changelog
> chore: dump version to 1.2.7

- src/dbus/applicationmanager1service.cpp
always update autostart application entry
Issue: https://github.com/linuxdeepin/developer-center/issues/8261
> fix: autostart desktop content error

- src/dbus/applicationservice.cpp
handle the exceptional case that location is -1
Issue: https://github.com/linuxdeepin/developer-center/issues/7964
> fix: crashed when removing a invalid index (-1)

- debian/changelog
release 1.2.8
Log: bump version to 1.2.8
> chore: bump version to 1.2.8

- debian/changelog
> chore: bump version to 1.2.9

- debian/changelog
> chore: bump version to 1.2.10

- src/dbus/applicationservice.cpp
> feat: Add DSG_APP_ID environment for application

- misc/hooks.d/debFix.sh
Only check for situations without shebang
Issue: https://github.com/linuxdeepin/developer-center/issues/8682
> fix: unable to launch application with non path exec field

- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationservice.cpp
- src/dbus/instanceservice.cpp
- src/dbus/mimemanager1service.cpp
- src/global.h
crash when Not called from DBus (ApplicationService::setAutoStart)
> fix crashed when autostart not existed

- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
- src/global.h
- src/systemdsignaldispatcher.cpp
- src/systemdsignaldispatcher.h
try add instance on JobNew signal
Issue: https://github.com/linuxdeepin/developer-center/issues/8879
> fix: instance not add if service start after AM

- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationservice.h
- src/dbus/mimemanager1service.cpp
- src/global.h
- tests/ut_applicationmanager.cpp
> fix: build faild

- src/dbus/applicationmanager1service.cpp
get all states `systemctl --state=help`
> chore: add instance on start state

- debian/changelog
release 1.2.14
Log: bump version to 1.2.14
> chore: bump version to 1.2.14

- debian/changelog
release 1.2.15
Log: bump version to 1.2.15
> chore: bump version to 1.2.15

- src/dbus/applicationservice.cpp
Issue: https://pms.uniontech.com/bug-view-243475.html
Log: Unable to run program with options
> fix: Unable to run program with options

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
> feat: add startupwmclass prop export

- debian/changelog
bump version 1.2.16
log: as title
> chore: bump version 1.2.16

- src/dbus/applicationmanager1service.cpp
treeland直接启动自启动应用
Log: treeland适配.
pms: TASK-361827
> feat:Treeland 适配

- debian/changelog
bump version 1.2.18
log: as title
> chore: bump version 1.2.18

- tests/ut_applicationmanager.cpp
修改测试用例不通过的问题
Log: 修改测试用例不通过的问题
pms: TASK-369021
> fix: 修改测试用例不通过的问题

- src/dbus/applicationmanager1service.cpp
应用更新不应生成家目录下自启动配置
Log: 修改部分应用无法自启动问题
pms: TASK-290821,TASK-277531
> fix: 修改部分应用无法自启动问题

- debian/changelog
bump version 1.2.19
log: as title
> chore: bump version 1.2.19

- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
没有正常删除桌面软链接
Log: 修改启动器问题
pms: BUG-290121, BUG-271019
> fix: 修复应用卸载后,启动器和桌面的应用图标依然存在问题

- debian/changelog
bump version 1.2.20
log: as title
> chore: bump version 1.2.20

- debian/changelog
bump version 1.2.21
log: as title
> chore: bump version 1.2.21

- src/dbus/applicationmanager1service.cpp
- src/dbus/applicationmanager1service.h
启动时候删除无效桌面应用图标
Log:
pms: BUG-297197
> fix: 修复在grub界面选择回退到之前的系统后，桌面上的图标显示为齿轮图标问题

- debian/changelog
bump version 1.2.22
log: as titl
> chore: bump version 1.2.22

- debian/changelog
> chore: bump version 1.2.23

- api/dbus/org.desktopspec.ApplicationManager1.Application.xml
- src/dbus/applicationservice.cpp
- src/dbus/applicationservice.h
dde-control-center requirements
pms: TASK-372065
> feat: provide the dbus attribute of desktopFile

- debian/changelog
release 1.2.24
Log: bump version to 1.2.24
> chore: bump version to 1.2.24

- src/dbus/applicationservice.cpp
多文件解析错误
Log:
pms: BUG-303135,BUG-300909,BUG-300199,BUG-299251,BUG-298875,BUG-298855
> fix: 修复多文件启动问题

- debian/changelog
release 1.2.25
Log: bump version to 1.2.25
> chore: bump version to 1.2.25
